#!/bin/sh -e

MISSING_DEPENDS="libQtDeclarative.so.4 (debian=libqt4-declarative)"

PACKAGE="dukto"
WEB_SITE="http://www.msec.it/blog/?page_id=11"
DEPENDS="gcc-lib-base libQtGui libQtNetwork libQtCore"
ROOT="$1"
[ -d "$ROOT" ] || ROOT=""

if test $(id -u) != 0 ; then
        echo -e "\nYou must be root to run `basename $0`."
        echo -e "Please type 'su' and root password to become super-user.\n"
        exit 0
fi

if [ -d $ROOT/var/lib/tazpkg/installed/$PACKAGE ]; then
	[ -n "$ROOT" ] && exit 1
	tazpkg remove $PACKAGE
	[ -d /var/lib/tazpkg/installed/$PACKAGE ] && exit 1
fi

TMP_DIR=/tmp/get-$PACKAGE-$$-$RANDOM
CUR_DIR=$(pwd)
mkdir -p $TMP_DIR && cd $TMP_DIR

URL="$(wget -O - "$WEB_SITE" | sed '/Linux download/!d;s/.*href="\([^"]*\).*/\1/')"
URL="$(wget -O - "$URL" | sed '/deb">i386/!d;s/.*href="\([^"]*\).*/\1/;q')"
FILE="$(basename $URL)"
wget -O $FILE "$URL"

if [ ! -f $FILE ]; then
	cd $CUR_DIR
	rm -rf $TMP_DIR
	echo "Could not download $FILE from $URL. Exiting."
	exit 1
fi

mkdir $PACKAGE
dpkg-deb -e $FILE $PACKAGE/meta
dpkg-deb -x $FILE $PACKAGE/fs
rm -rf $PACKAGE/fs/usr/share
# extracted pkg can be removed: Save RAM
rm -f $FILE
sed '/^Description:/,$!d;s/^Description://' \
	< $PACKAGE/meta/control > $PACKAGE/description.txt

MAINTAINER="$(sed '/^Maintainer:/!d;s/^Maintainer: //' $PACKAGE/meta/control)"
SHORT_DESC="$(sed '/^Description:/!d;s/^Description: //' $PACKAGE/meta/control)"
VERSION="$(sed '/^Version:/!d;s/^Version: //' $PACKAGE/meta/control)"
rm -rf $PACKAGE/meta
mv $PACKAGE $PACKAGE-$VERSION

cat > $PACKAGE-$VERSION/receipt <<EOT
PACKAGE="$PACKAGE"
VERSION="$VERSION"
CATEGORY="non-free"
MAINTAINER="$MAINTAINER"
SHORT_DESC="$SHORT_DESC."
DEPENDS="$DEPENDS"
WEB_SITE="$WEB_SITE"
EOT

# Pack
tazpkg pack $PACKAGE-$VERSION

# Clean to save RAM memory
rm -rf $PACKAGE-$VERSION

# Install pseudo package
tazpkg install $PACKAGE-$VERSION.tazpkg --root=$ROOT
case " $@ " in
*\ --k*) mv $PACKAGE-$VERSION.tazpkg $CUR_DIR ;;
esac

# Clean
cd $CUR_DIR
rm -rf $TMP_DIR

